# Generated by Django 4.2.6 on 2024-02-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
